import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from './context/provider'
const inter = Inter({ subsets: ['latin'] })
import "tw-elements/dist/css/tw-elements.min.css";
import UserDataProvider from './context/userdata/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <UserDataProvider>
      <body className='bg-foreground-light dark:bg-foreground-dark min'>{children}</body>
      </UserDataProvider>
      </AuthProvider>
    </html>
  )
}
